#!/usr/bin/env python
"""render_report.py — assemble REPORT_tables.md from results/*.json (health_metrics.py output), masks/mask_summary.json, calib/costb_fee_steady.json, logs/*.
Every number in the tables is read from those files; nothing is computed here except unit conversions already defined in health_metrics.py (none) and simple differences
between two JSON numbers where a column says Δ. Prints the markdown to stdout."""
import json, os, glob, time, hashlib
ROOT = "/workspace/review_scratch/health_check"
ARMS = [("eq_patched_pinned_log_s42", "REF: M1+T400 (trade set = top-400 by qvk), log, s42, device default cost — equivalence artifact, NOT a PREREG arm"),
        ("UPIT_prod_s42_cdef", "U-PIT · prod · s42 · device default cost"), ("UPIT_prod_s2027_cdef", "U-PIT · prod · s2027 · device default cost"),
        ("UPIT_log_s42_cdef", "U-PIT · log · s42 · device default cost"), ("UPIT_log_s2027_cdef", "U-PIT · log · s2027 · device default cost"),
        ("UPIT_prod_s42_ccal", "U-PIT · prod · s42 · live fee-only cost"), ("UPIT_prod_s2027_ccal", "U-PIT · prod · s2027 · live fee-only cost"),
        ("UPIT_log_s42_ccal", "U-PIT · log · s42 · live fee-only cost"), ("UPIT_log_s2027_ccal", "U-PIT · log · s2027 · live fee-only cost"),
        ("UFROZEN_prod_s42_ccal", "U-FROZEN · prod · s42 · live fee-only cost"), ("UFROZEN_prod_s2027_ccal", "U-FROZEN · prod · s2027 · live fee-only cost")]
SHORT = {"eq_patched_pinned_log_s42": "REF T400/log/42", "UPIT_prod_s42_cdef": "PIT/prod/42/def", "UPIT_prod_s2027_cdef": "PIT/prod/2027/def", "UPIT_log_s42_cdef": "PIT/log/42/def", "UPIT_log_s2027_cdef": "PIT/log/2027/def",
         "UPIT_prod_s42_ccal": "PIT/prod/42/cal", "UPIT_prod_s2027_ccal": "PIT/prod/2027/cal", "UPIT_log_s42_ccal": "PIT/log/42/cal", "UPIT_log_s2027_ccal": "PIT/log/2027/cal", "UFROZEN_prod_s42_ccal": "FRZ/prod/42/cal", "UFROZEN_prod_s2027_ccal": "FRZ/prod/2027/cal"}
PRIMARY = ["UPIT_prod_s42_ccal", "UPIT_prod_s2027_ccal"]; SLICE_ARMS = ["UPIT_prod_s42_ccal", "UPIT_prod_s2027_ccal", "UPIT_log_s42_ccal", "UPIT_log_s2027_ccal", "UFROZEN_prod_s42_ccal", "eq_patched_pinned_log_s42"]
WINS_MAIN = ["2024", "2024-H1", "2024-H2", "2025", "2026->cut", "2024->26", "2025->26"]; QS = [f"{y}-Q{q}" for y in (2024, 2025, 2026) for q in (1, 2, 3, 4) if not (y == 2026 and q == 4)]
R = {}
for tag, _ in ARMS:
    p = f"{ROOT}/results/{tag}.json"
    if os.path.exists(p): R[tag] = json.load(open(p))
def f(v, nd=2):
    if v is None: return "—"
    if isinstance(v, bool): return str(v)
    if isinstance(v, str): return v
    if isinstance(v, (int,)) and not isinstance(v, bool): return str(v)
    try: return f"{float(v):.{nd}f}"
    except Exception: return str(v)
def ci(b, k="mean_ci95", nd=2):
    if not b or b.get(k) is None or b[k][0] is None: return "—"
    return f"[{f(b[k][0], nd)}, {f(b[k][1], nd)}]"
def sha16(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()[:16]
out = []; P = out.append
P("<!-- generated by render_report.py; every number is read from results/<tag>.json (health_metrics.py), masks/mask_summary.json, calib/costb_fee_steady.json, logs/* -->")
# ── T1 arm index
P("\n### T1. Arms (device w10_health.py; artifact and results receipts)\n")
P("| tag | form | n anchors | first → last | artifact sha256[:16] | results json sha256[:16] |"); P("|---|---|---|---|---|---|")
for tag, lab in ARMS:
    if tag not in R: P(f"| {tag} | {lab} | MISSING | | | |"); continue
    o = R[tag]; P(f"| {tag} | {lab} | {o['n_anchors_total']} | {o['first']} → {o['last']} | {o['artifact_sha256'][:16]} | {sha16(f'{ROOT}/results/{tag}.json')} |")
# ── T2 masks
S = json.load(open(f"{ROOT}/masks/mask_summary.json"))
P("\n### T2. Universe masks — yearly mean counts on the device's anchor grid (masks/mask_summary.json)\n")
P("| year | U-PIT allowed | U-PIT tradeable | U-FROZEN allowed | U-FROZEN tradeable | no-mask tradeable (829 base) | allowed in both | both / 449 | tradeable in both |"); P("|---|---|---|---|---|---|---|---|---|")
for y in sorted(S["masks"]["UPIT"]):
    a = S["masks"]["UPIT"][y]; b = S["masks"]["UFROZEN"][y]; n = S["masks"]["NO_MASK_829"][y]; o = S["overlap"][y]
    P(f"| {y} | {f(a['allowed_mean'],1)} | {f(a['tradeable_mean'],1)} | {f(b['allowed_mean'],1)} | {f(b['tradeable_mean'],1)} | {f(n['tradeable_mean'],1)} | {f(o['allowed_both_mean'],1)} | {f(o['allowed_both_over_449'],3)} | {f(o['tradeable_both_mean'],1)} |")
P(f"\ntradeable = mask ∧ qv4h ≥ 2.5e5 ∧ finite y4 (device `sel` without the ≥80 gate). Listings by year (first 5m bar): {S['listing_by_year']}. BTC 30-day realised vol, yearly mean %: {S['btc_rv30_yearly_mean_pct']}.")
P("\nU-PIT month rows (first 3 and last 3 of 56): " + "; ".join(f"{m['month']}: listed {m['n_listed']}, eligible {m['n_elig']}, top {m['n_top']}, 449th 30d vol {f(m['vol30_449th_usd']/1e6,1) if m['vol30_449th_usd'] else '—'} M USDT" for m in S["months"][:3] + S["months"][-3:]))
# ── T3 headline per gross
P("\n### T3. Headline by window — mean net bps per anchor per unit gross [CI95, UTC-day block bootstrap 2000×] (executor caliber; ×2×2190/1e4 = %/yr of NAV at 2×)\n")
P("| arm | " + " | ".join(WINS_MAIN) + " |"); P("|---|" + "---|" * len(WINS_MAIN))
for tag, _ in ARMS:
    if tag not in R: continue
    row = []
    for wn in WINS_MAIN:
        w = R[tag]["windows"].get(wn, {})
        if w.get("skipped") or "per_gross" not in w: row.append("—"); continue
        row.append(f"{f(w['per_gross']['mean_bps_anchor'],3)} {ci(w.get('boot'))}")
    P(f"| {SHORT[tag]} | " + " | ".join(row) + " |")
P("\n### T3b. Anchor Sharpe (√2190, leverage-invariant) [CI95]\n")
P("| arm | " + " | ".join(WINS_MAIN) + " |"); P("|---|" + "---|" * len(WINS_MAIN))
for tag, _ in ARMS:
    if tag not in R: continue
    row = []
    for wn in WINS_MAIN:
        w = R[tag]["windows"].get(wn, {})
        if w.get("skipped") or "per_gross" not in w: row.append("—"); continue
        row.append(f"{f(w['per_gross']['sharpe_anchor'],2)} {ci(w.get('boot'), 'sharpe_ci95', 2)}")
    P(f"| {SHORT[tag]} | " + " | ".join(row) + " |")
# ── T4 NAV at 2x
P("\n### T4. NAV at the live leverage 2.0× — arithmetic %/yr · CAGR % · max drawdown % · worst UTC day % · days < −2% / < −5% / < −10% (n of days)\n")
P("| arm | " + " | ".join(WINS_MAIN) + " |"); P("|---|" + "---|" * len(WINS_MAIN))
for tag, _ in ARMS:
    if tag not in R: continue
    row = []
    for wn in WINS_MAIN:
        w = R[tag]["windows"].get(wn, {})
        if w.get("skipped") or "by_L" not in w: row.append("—"); continue
        d = w["by_L"]["2.0"]; row.append(f"{f(d['arith_pct_yr'],1)} · {f(d['cagr_pct'],1)} · DD {f(d['maxdd_pct'],1)} · wd {f(d['worst_day_pct'],2)} · {d['days_below_2pct']}/{d['days_below_5pct']}/{d['days_below_10pct']} of {w['n_days']}")
    P(f"| {SHORT[tag]} | " + " | ".join(row) + " |")
# ── T5 leverage table for primary arms
P("\n### T5. Leverage table — primary arms (U-PIT, prod caliber, live fee-only cost), L ∈ {2.0, 2.5, 3.0}\n")
KEYS = [("arith_pct_yr", "arith %/yr"), ("cagr_pct", "CAGR %"), ("total_return_pct", "total %"), ("vol_pct_yr_anchor", "vol %/yr"), ("sharpe_daily", "Sharpe daily"), ("sortino_daily", "Sortino daily"), ("maxdd_pct", "maxDD %"), ("maxdd_span_days", "maxDD span d"), ("maxdd_recovered", "recovered"),
        ("longest_dd_days", "longest DD d"), ("worst_day_pct", "worst day %"), ("worst_week_pct", "worst week %"), ("worst_month_pct", "worst month %"), ("worst_month", "worst month"), ("months_negative", "neg months"), ("n_months", "n months"),
        ("days_below_2pct", "days<−2%"), ("share_days_below_2pct", "share<−2%"), ("days_below_5pct", "days<−5%"), ("share_days_below_5pct", "share<−5%"), ("days_below_10pct", "days<−10%"), ("win_rate_day", "win day"),
        ("anchor_p1_pct", "anchor p1 %"), ("anchor_p5_pct", "anchor p5 %"), ("anchor_min_pct", "anchor min %"), ("sum8_p5_pct", "8-anchor p5 %"), ("sum8_min_pct", "8-anchor min %"), ("var99_day_pct", "VaR99 day %"), ("cvar99_day_pct", "CVaR99 day %"),
        ("min_margin_ratio_anchor", "min equity/gross (anchor)"), ("touches_maint_anchor", "touches 1.5% (anchor)"), ("min_margin_ratio_8anchor", "min equity/gross (8 anchors)"), ("touches_maint_8anchor", "touches 1.5% (8 anchors)")]
for wn in ["2024->26", "2025->26", "2026->cut", "2024", "2025"]:
    P(f"\n**{wn}**\n"); hdr = [f"{SHORT[t]} L={L}" for t in PRIMARY for L in ("2.0", "2.5", "3.0")]
    P("| metric | " + " | ".join(hdr) + " |"); P("|---|" + "---|" * len(hdr))
    for k, lab in KEYS:
        row = []
        for t in PRIMARY:
            for L in ("2.0", "2.5", "3.0"):
                w = R.get(t, {}).get("windows", {}).get(wn, {}); d = w.get("by_L", {}).get(L)
                row.append(f(d.get(k), 2) if d else "—")
        P(f"| {lab} | " + " | ".join(row) + " |")
    row = []
    for t in PRIMARY:
        for L in ("2.0", "2.5", "3.0"):
            w = R.get(t, {}).get("windows", {}).get(wn, {}); d = w.get("by_L", {}).get(L); rs = d.get("rolling90d_sharpe", {}) if d else {}
            row.append(f"{f(rs.get('p5'))} / {f(rs.get('median'))} / {f(rs.get('p95'))} (n {rs.get('n_windows', 0)})")
    P("| rolling 90-day daily Sharpe p5 / median / p95 | " + " | ".join(row) + " |")
# ── T6 quarterly
P("\n### T6. Calendar quarters — mean net bps per anchor per gross · NAV total return % at 2× (compounded) · max DD % at 2×\n")
P("| arm | " + " | ".join(QS) + " |"); P("|---|" + "---|" * len(QS))
for tag, _ in ARMS:
    if tag not in R: continue
    row = []
    for q in QS:
        w = R[tag]["windows"].get(q, {})
        if w.get("skipped") or "by_L" not in w: row.append("—"); continue
        d = w["by_L"]["2.0"]; row.append(f"{f(w['per_gross']['mean_bps_anchor'],2)} · {f(d['total_return_pct'],1)}% · DD {f(d['maxdd_pct'],1)}")
    P(f"| {SHORT[tag]} | " + " | ".join(row) + " |")
# ── T7 monthly primary
P("\n### T7. Calendar months 2024-01 → 2026-08 (to cut) — NAV % at 2× (compounded) · mean bps/anchor per gross; primary arms and the REF form\n")
cols = PRIMARY + ["UFROZEN_prod_s42_ccal", "eq_patched_pinned_log_s42"]
P("| month | " + " | ".join(SHORT[c] for c in cols) + " |"); P("|---|" + "---|" * len(cols))
months = sorted(set(m for c in cols if c in R for m in R[c]["monthly"]))
for mo in months:
    P(f"| {mo[:4]}-{mo[4:]}{' (to cut 08-10)' if mo == '202608' else ''} | " + " | ".join((f"{f(R[c]['monthly'][mo]['nav_pct_at_2x'],1)}% · {f(R[c]['monthly'][mo]['mean_bps_anchor_per_gross'],2)}" if c in R and mo in R[c]["monthly"] else "—") for c in cols) + " |")
# ── T8 slices
for nm, title in (("sigma_fund", "σ_fund (bps/8h, META members, 30-anchor trailing mean)"), ("breadth_nsel", "breadth = nsel (tradeable names)"), ("neg_fund_share", "negative-funding share of members (30-anchor trailing mean)"), ("btc_rv30", "BTC 30-day realised vol (annualised %)")):
    P(f"\n### T8-{nm}. Slice 2024→cut: {title} — mean net bps/anchor per gross [CI95] · anchor Sharpe · NAV %/yr at 2× (arith) · n\n")
    cols = [c for c in SLICE_ARMS if c in R]
    a0 = R[cols[0]]["slices"][nm]; P(f"definition: {a0['definition']}. Causal cuts at window end {a0['causal_cuts_at_window_end']}; descriptive (window) cuts {a0['descriptive_cuts_2024_cut']}.\n")
    P("| bucket | " + " | ".join(SHORT[c] for c in cols) + " |"); P("|---|" + "---|" * len(cols))
    for kind in ("causal", "descriptive"):
        for b in ("low", "mid", "high"):
            row = []
            for c in cols:
                v = R[c]["slices"][nm][kind].get(b, {})
                row.append(f"{f(v.get('mean_bps_anchor_per_gross'),2)} {ci(v)} · S {f(v.get('sharpe_anchor'),2)} · {f(v.get('nav_pct_yr_at_2x'),0)}%/yr · n {v.get('n_anchors')}" if v.get("n_anchors", 0) >= 12 else f"n {v.get('n_anchors', 0)}")
            P(f"| {kind} {b} (var mean {f(R[cols[0]]['slices'][nm][kind].get(b, {}).get('regime_var_mean'),2)}) | " + " | ".join(row) + " |")
# ── T9 costs / carry / turnover
P("\n### T9. Turnover, cost and carry per window (per unit gross; cost_ex and carry_ex from the rec; shares = Σ over the window / Σ gross price P&L)\n")
P("| arm | window | turnover/gross per anchor | cost bps/anchor/gross | cost %/yr NAV @2× | carry paid bps/anchor/gross | carry %/yr NAV @2× | gross price P&L bps/anchor/gross | cost share | carry share | net bps/anchor/gross |"); P("|---|---|---|---|---|---|---|---|---|---|---|")
for tag, _ in ARMS:
    if tag not in R: continue
    for wn in ("2024->26", "2025->26", "2026->cut"):
        w = R[tag]["windows"].get(wn, {})
        if w.get("skipped") or "form" not in w: continue
        fm = w["form"]; P(f"| {SHORT[tag]} | {wn} | {f(fm['turnover_per_gross_mean'],4)} | {f(fm['cost_ex_bps_per_gross_mean'],3)} | {f(fm['cost_ex_bps_per_gross_mean']*2*2190/1e4*100,2)} | {f(fm['carry_paid_bps_per_gross_mean'],3)} | {f(fm['carry_paid_bps_per_gross_mean']*2*2190/1e4*100,2)} | {f(fm['pnl_ex_bps_per_gross_mean'],3)} | {f(fm['cost_share_of_gross_pnl'],3)} | {f(fm['carry_share_of_gross_pnl'],3)} | {f(w['per_gross']['mean_bps_anchor'],3)} |")
# ── T9b default vs calibrated cost delta
P("\n### T9b. Δ(live fee-only − device default cost), same universe/caliber/seed — mean net bps/anchor per gross (paired by construction: identical books, only COST_B differs)\n")
P("| pair | 2024 | 2025 | 2026->cut | 2024->26 | 2025->26 |"); P("|---|---|---|---|---|---|")
for cal in ("prod", "log"):
    for s in ("42", "2027"):
        a, b = f"UPIT_{cal}_s{s}_ccal", f"UPIT_{cal}_s{s}_cdef"
        if a in R and b in R:
            P(f"| {SHORT[a]} − {SHORT[b]} | " + " | ".join(f"{f(R[a]['windows'][wn]['per_gross']['mean_bps_anchor'] - R[b]['windows'][wn]['per_gross']['mean_bps_anchor'],3)} (cost {f(R[b]['windows'][wn]['form']['cost_ex_bps_per_gross_mean'],3)}→{f(R[a]['windows'][wn]['form']['cost_ex_bps_per_gross_mean'],3)})" for wn in ("2024", "2025", "2026->cut", "2024->26", "2025->26")) + " |")
# ── T9c U-FROZEN vs U-PIT
P("\n### T9c. Δ(U-FROZEN − U-PIT), prod caliber, live fee-only cost — mean net bps/anchor per gross (unpaired books; U-FROZEN carries look-ahead selection)\n")
P("| pair | 2024 | 2025 | 2026->cut | 2024->26 | 2025->26 |"); P("|---|---|---|---|---|---|")
for s in ("42", "2027"):
    a, b = f"UFROZEN_prod_s{s}_ccal", f"UPIT_prod_s{s}_ccal"
    if a in R and b in R:
        P(f"| {SHORT[a]} − {SHORT[b]} | " + " | ".join(f"{f(R[a]['windows'][wn]['per_gross']['mean_bps_anchor'] - R[b]['windows'][wn]['per_gross']['mean_bps_anchor'],3)} (S {f(R[a]['windows'][wn]['per_gross']['sharpe_anchor'])} vs {f(R[b]['windows'][wn]['per_gross']['sharpe_anchor'])})" for wn in ("2024", "2025", "2026->cut", "2024->26", "2025->26")) + " |")
# ── T10 form descriptors
P("\n### T10. Replay form by year — mean gross of the unit book, tradeable names (nsel), king seat w3_king, net long, stop fires, king/fund leg returns (bps/anchor unit-gross rank book)\n")
P("| arm | window | gross_total | nsel | w3_king | w3_fund | net long | fires | leg_king | leg_fund |"); P("|---|---|---|---|---|---|---|---|---|---|")
for tag, _ in ARMS:
    if tag not in R: continue
    for wn in ("2024-H1", "2024-H2", "2025", "2026->cut"):
        w = R[tag]["windows"].get(wn, {})
        if w.get("skipped") or "form" not in w: continue
        fm = w["form"]; P(f"| {SHORT[tag]} | {wn} | {f(fm['gross_total_mean'],3)} | {f(fm['nsel_mean'],0)} | {f(fm['w3_king_mean'],3)} | {f(fm['w3_fund_mean'],3)} | {f(fm['netlong_mean'],4)} | {fm['fires_total']} | {f(fm['leg_king_mean'],3)} | {f(fm['leg_fund_mean'],3)} |")
# ── T11 unit-book reconciliation
P("\n### T11. Caliber reconciliation — unit replay book (net_ex, gross floats; = RECEIPT_EX / earlier STATE numbers) vs per-gross (executor caliber, this report)\n")
P("| arm | window | unit-book net_ex bps/anchor | unit-book Sharpe | per-gross bps/anchor | per-gross Sharpe | mean gross_total |"); P("|---|---|---|---|---|---|---|")
for tag in ["eq_patched_pinned_log_s42"] + PRIMARY:
    if tag not in R: continue
    for wn in ("2024", "2025", "2026->cut", "2024->26"):
        w = R[tag]["windows"][wn]; P(f"| {SHORT[tag]} | {wn} | {f(w['unit_book']['net_ex_mean_bps_anchor'],3)} | {f(w['unit_book']['sharpe_anchor'],2)} | {f(w['per_gross']['mean_bps_anchor'],3)} | {f(w['per_gross']['sharpe_anchor'],2)} | {f(w['form']['gross_total_mean'],3)} |")
# ── T12 post-cut
P("\n### T12. 2026-08-11 → 2026-08-30 (after the F10 cut; F10 leg absent ⇒ NOT the live form; shown only because it overlaps the live window 08-26 →)\n")
P("| arm | n anchors | mean bps/anchor/gross | Sharpe | NAV total % @2× | worst day % @2× |"); P("|---|---|---|---|---|---|")
for tag, _ in ARMS:
    if tag not in R: continue
    w = R[tag]["windows"].get("2026-postcut", {})
    if w.get("skipped") or "by_L" not in w: continue
    P(f"| {SHORT[tag]} | {w['n_anchors']} | {f(w['per_gross']['mean_bps_anchor'],3)} | {f(w['per_gross']['sharpe_anchor'],2)} | {f(w['by_L']['2.0']['total_return_pct'],2)} | {f(w['by_L']['2.0']['worst_day_pct'],2)} |")
# ── T13 receipts
P("\n### T13. Receipts\n")
cb = json.load(open(f"{ROOT}/calib/costb_fee_steady.json"))
P(f"- COST_B override (calib/costb_fee_steady.json sha256[:16] {sha16(f'{ROOT}/calib/costb_fee_steady.json')}): " + "; ".join(f"{t['name']}: maker {t['maker_bps']} / taker {t['taker_bps']} bps, maker share {t['maker_share']}, maker fill ratio {t['fill_ratio_maker']} (after top-up {t['fill_ratio_after_topup']})" for t in cb["tiers"]) + f". Source: {cb['source']}. cost_calib.json sha256 {cb['cost_calib_json_sha256'][:16]}…, its self_sha256 {cb['cost_calib_self_sha256'][:16]}…, run {cb['cost_calib_run_utc']}.")
P(f"- Not used (INFERRED): fee − raw markout per tier {cb['not_used']['fee_minus_raw_markout_steady']}; fee − delay-reweighted markout pooled {cb['not_used']['fee_minus_delay_reweighted_markout_pooled']}. Why: {cb['not_used']['why']}")
P(f"- Twin band (cost-calib §9, n={cb['twin_band']['n']}): paper(shifted) − twin {cb['twin_band']['paper_shifted_minus_twin_bps_per_anchor']} bps/anchor of gross, CI95 {cb['twin_band']['ci95']}; twin + funding {cb['twin_band']['twin_plus_funding_bps_per_anchor']} CI95 {cb['twin_band']['ci95_tf']}.")
for lf in ("logs/check_equiv.log", "logs/chain_all.log"):
    P(f"\n`{lf}`:\n```"); P(open(f"{ROOT}/{lf}").read().strip()); P("```")
P("\n`logs/commands.txt` (every device run, verbatim; earlier UPIT_*_cdef runs on the pre-fix mask were overwritten by the final chain — see the last CMD/END pair per tag):\n```")
P(open(f"{ROOT}/logs/commands.txt").read().strip()); P("```")
print("\n".join(out))
