#!/usr/bin/env python3
"""ens_combo.py — STEP 3 of docs/PREREG_f10_seed_ensemble_book_2026-09-23.md (45aba1f3f): the NEW combo targets with a chosen F10 score file,
generated by the researcher's OWN pinned code (continuous_combo.evolve / verify_training, combo_target.step, book_universe.align, imported
read-only from /workspace/codex_research/QNT-2026-0907/combo_20260923/devices with python -B; nothing is written into that tree).

Why a wrapper: continuous_combo.main() (sha 1501c9f6) hard-codes the F10 source as corrected_combo_v1d/f10_s{--seed ∈ {42, 2027}} and the output as
corrected_combo_v1d/combo_s{seed}. This file is main() transcribed statement by statement with exactly TWO substitutions:
  (S1) the F10 score file: `froot/'F10_OOF.npz'` → F10 (for --f10 s42 / s2027 it IS froot/'F10_OOF.npz'; for --f10 ens it is the ENS file,
       whose own receipt must pin both seeds' F10_OOF shas, and BOTH seeds' training chains are verified exactly as main() verifies one);
  (S2) the output directory: `r/f'combo_s{seed}'` → --out (a new directory under the ENS work root; exist_ok=False as in main()).
Everything else — every input path, every identity assertion, the `use` extent, book_legal, config['params'], the two policies, evolve()'s
arguments, np.savez_compressed with the same keys, the per-year summary and the TARGET_RECEIPT fields the adapter reads — is main()'s.
The positive control (--f10 s42) must reproduce the researcher's combo_s42 (scaled_diagnostic 4dec6b38, literal cae52acf) array by array, bit
for bit (ens_combo_compare.py); that is the proof that the transcription changed nothing else.
usage: env -i PATH=/usr/bin:/bin HOME=/root /workspace/venv/bin/python -B ens_combo.py PATH,HOME,LC_CTYPE --f10 {s42,s2027,ens}
       [--ens-npz P --ens-receipt P] --out DIR
"""
import os, sys, json, pathlib, argparse, collections, datetime, hashlib

WL = set(sys.argv[1].split(",")); extra = sorted(set(os.environ) - WL); assert not extra, f"env outside whitelist: {extra}"
CR = pathlib.Path("/workspace/codex_research/QNT-2026-0907/combo_20260923")
PIN_SRC = {CR / "devices/continuous_combo.py": "1501c9f63641bf447c4cb33661d08da25ced0948f9fae63cebb44cdfd1995d21",
           CR / "devices/combo_target.py": "d7577e824298fb90a554f35ac9c4d634202a4ed7e4e00cabc597a2d4eafdb544",
           CR / "devices/book_universe.py": "90e332cc27cf8f34aabcac13f9829f84e463ffa900efbe554e17c07436e8dcca",
           CR / "devices/build_combo_inputs.py": "eb708c5a99f09d9967b1c4326c957331c9ca20260dfc8649b1c4179bd53a9390",
           CR / "vendor_live/fea171/combo_stage.py": "fb5a94074583b328b949cd08767c031d9eb705fbdc23d6a371d9bd657b3ca4a8"}


def _sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 22), b""): h.update(b)
    return h.hexdigest()


for p, h in PIN_SRC.items(): assert _sha(p) == h, f"researcher source drift {p}"
sys.dont_write_bytecode = True
sys.path.insert(0, str(CR / "devices"))
import numpy as np
import continuous_combo as CC                      # evolve, verify_training; imports combo_target.step and book_universe
from book_universe import align as align_universe, PATH as UNIVERSE_PATH, SHA as UNIVERSE_SHA


def verify_seed_chain(r, seed, sha, ident):
    """main()'s verification of ONE seed's F10 training chain, verbatim (froot, rec, pred_sha256, verify_training, folds, inputs, sources)"""
    froot = r / f'f10_s{seed}'
    for p in (froot / 'F10_OOF.npz', froot / 'TRAIN_RECEIPT.json'): ident[str(p)] = sha(p)
    rec = json.loads((froot / 'TRAIN_RECEIPT.json').read_text())
    assert rec['status'] == 'ALL_DECLARED_FOLDS_SCORED_NOT_COMBO_CERTIFIED' and rec['pred_sha256'] == ident[str(froot / 'F10_OOF.npz')]
    CC.verify_training(froot, rec, seed, sha)
    assert set(rec['folds']) == set(rec['expected_folds']) and len(rec['folds']) == len(rec['expected_folds'])
    for p, h in rec['inputs'].items(): assert sha(p) == h, ('training input drift', p)
    for p, h in rec['sources'].items(): assert sha(p) == h, ('training source drift', p)
    return froot, rec


def main():
    from build_combo_inputs import ROOT, sha
    ap = argparse.ArgumentParser(); ap.add_argument('--f10', choices=('s42', 's2027', 'ens'), required=True); ap.add_argument('--ens-npz'); ap.add_argument('--ens-receipt')
    ap.add_argument('--out', required=True); args = ap.parse_args(sys.argv[2:])
    r = ROOT / 'corrected_combo_v1d'
    paths = [r / 'data/dlw_targets.npz', r / 'data/f10v2_legs.npz', r / 'data/LEGS_RECEIPT.json', r / 'data/funding_state.npz', r / 'BUILD_RECEIPT.json', ROOT / 'vendor_live/shadow_bundle/config.json']
    ident = {str(p): sha(p) for p in paths}; br = json.loads(paths[4].read_text()); lr = json.loads(paths[2].read_text())
    seeds = (42, 2027) if args.f10 == 'ens' else (int(args.f10[1:]),)
    recs = {}
    for seed in seeds:
        froot, rec = verify_seed_chain(r, seed, sha, ident); recs[seed] = rec
        for p in paths[:5]:
            if str(p) in rec['inputs']: assert ident[str(p)] == rec['inputs'][str(p)]
    # (S1) the F10 score file
    if args.f10 == 'ens':
        er = json.loads(pathlib.Path(args.ens_receipt).read_text()); f10_path = pathlib.Path(args.ens_npz)
        ident[str(f10_path)] = sha(f10_path); ident[str(args.ens_receipt)] = sha(args.ens_receipt)
        assert er['device'] == 'ens_build.py' and er['output']['sha256'] == ident[str(f10_path)], 'ENS file vs its receipt'
        assert er['inputs']['f10_s42']['sha256'] == ident[str(r / 'f10_s42/F10_OOF.npz')] == recs[42]['pred_sha256'], 'ENS input s42 vs verified chain'
        assert er['inputs']['f10_s2027']['sha256'] == ident[str(r / 'f10_s2027/F10_OOF.npz')] == recs[2027]['pred_sha256'], 'ENS input s2027 vs verified chain'
        assert er['inputs']['dlw_targets']['sha256'] == ident[str(paths[0])], 'ENS members source'
        assert er['one_seed_only_names']['total'] == 0, 'one-seed-only names present: report before any combo (prereg expects 0)'
    else:
        f10_path = r / f'f10_s{seeds[0]}' / 'F10_OOF.npz'
    assert ident[str(paths[1])] == lr['artifact_sha']; assert sha(ROOT / 'devices/combo_legs.py') == lr['source_sha']
    for p, h in lr['input_sha'].items(): assert sha(p) == h, ('leg upstream drift', p)
    assert ident[str(paths[0])] == br['artifacts'][str(paths[0])] and ident[str(paths[3])] == br['artifacts'][str(paths[3])]
    t = np.load(paths[0], allow_pickle=True); leg = np.load(paths[1]); fund = np.load(paths[3]); score = np.load(f10_path); a = t['E_ts']; syms = t['symbols']
    for z in (leg, fund, score): assert np.array_equal(z['E_ts'], a) and np.array_equal(z['symbols'], syms)
    # No synthetic F10 predictions for 2022. Start hypothetical strategy in cash.
    assert sha(UNIVERSE_PATH) == UNIVERSE_SHA, 'universe content identity'
    universe = np.load(UNIVERSE_PATH)
    # Explicit common extent, never fabricate rows beyond the frozen book axis.
    use = (a >= 1672531200) & (a <= universe['ts'][-1]); a = a[use]
    book_legal = align_universe(a, syms, universe) & fund['legal'][use]
    ident[UNIVERSE_PATH] = UNIVERSE_SHA
    config = json.loads(paths[-1].read_text())
    sources = {str(p): sha(p) for p in [pathlib.Path(CC.__file__), ROOT / 'devices/combo_target.py', ROOT / 'devices/book_universe.py', ROOT / 'vendor_live/fea171/combo_stage.py']}
    sources[str(pathlib.Path(__file__).resolve())] = sha(pathlib.Path(__file__).resolve())
    # (S2) the output directory
    out = pathlib.Path(args.out); out.mkdir(exist_ok=False)
    summary = {}
    for policy in ('literal', 'scaled_diagnostic'):
        result = CC.evolve(a, leg['KZ'][use], score['P'][use], leg['ZFD'][use], leg['WL'][use], fund['rn8'][use], list(t['members'][use]), t['qvk'][use], book_legal, leg['ready'][use], config['params'], policy)
        p = out / (policy + '.npz'); tmp = p.with_suffix('.tmp.npz'); np.savez_compressed(tmp, E_ts=a, symbols=syms, **result); tmp.replace(p)
        counts = dict(collections.Counter(result['reason'])); years = {}
        yr = np.array([datetime.datetime.fromtimestamp(int(x), datetime.timezone.utc).year for x in a])
        for y in np.unique(yr):
            m = yr == y; years[str(y)] = {'anchors': int(m.sum()), 'publish': int(result['trade_mask'][m].sum()), 'mean_producer_gross': float(np.abs(result['raw'][m]).sum(1).mean())}
        summary[policy] = {'path': str(p), 'sha': sha(p), 'reasons': counts, 'years': years}
    for p, h in ident.items(): assert sha(p) == h
    for p, h in sources.items(): assert sha(p) == h
    receipt = {'status': 'CORRECTED_CANDIDATE_TARGETS_NOT_EXECUTION_PNL', 'seed': ('ENS(42,2027)' if args.f10 == 'ens' else seeds[0]), 'f10_source': args.f10,
               'f10_score_file': {'path': str(f10_path), 'sha256': ident[str(f10_path)]}, 'inputs': ident, 'sources': sources, 'policies': summary,
               'state_init': 'zero at 2023-01-01; hypothetical common start, not live archived state', 'hold_contract': 'trade_mask False = maintain quantities, never King substitution',
               'limits': ['not whole producer parity: causal historical funding base and corrected features explicitly differ', 'no execution/cash or policy-stop result',
                          'scaled_diagnostic changes historical publication gate; never current-live literal'],
               'generator': 'ens_combo.py = continuous_combo.main() with (S1) F10 score file and (S2) output dir substituted; positive control --f10 s42 vs combo_s42'}
    (out / 'TARGET_RECEIPT.json').write_text(json.dumps(receipt, indent=2, allow_nan=False))
    print(f"ENS_COMBO DONE f10={args.f10} out={out} scaled_sha={summary['scaled_diagnostic']['sha']} literal_sha={summary['literal']['sha']} receipt_sha={sha(out / 'TARGET_RECEIPT.json')}", flush=True)


if __name__ == '__main__': main()
