#!/usr/bin/env python3
"""ens_make_config.py — the frozen run configuration of NEW_ENS (prereg 45aba1f3f §2 / step 5), derived BY COPY from Stage 1's frozen
RUN_CONFIG_OVN_NEW_s42_2026-09-23.json (sha 162239b6, committed e6d8f6680), with a leaf-level diff asserted before anything is written.
Changed leaves (and nothing else):
  labels      config / status / created_utc / object / pending / ovn.role / f10ens (new provenance block)
  targets     runs[*].targets.arm and runs[*].targets.sources (the adapter's TARGETS_NEW_ENS npz + receipt, shas pinned);
              runs[*].arm / tag / role (run naming); new_lineage (adapter receipt / NEW_ENS target receipt / sources)
  output root paths.pod_root: /dev/shm/ovn_2026-09-23 → /dev/shm/f10_ens_2026-09-23 — an OUTPUT location, not a setting: keeping it would write
              this arm's path files into Stage 1's directory, which this task must never write to. Declared, not hidden.
Every setting (window, 32 seeds, gross, chase, decision / stop offsets, events, policies, cost cells, calibration, simulator pins, launch
limits) is byte-identical to NEW_s42's. The same five runs are kept (main scaled; lit; three cost cells) so the settings are identical; only the
main scaled run is a criterion input (prereg §2 R-main).
usage: env -i PATH=/usr/bin:/bin HOME=/root /workspace/venv/bin/python -B ens_make_config.py PATH,HOME,LC_CTYPE <template NEW_s42 config> <template sha>
       <adapter receipt NEW_ENS> <adapter npz path> <out config> <out diff receipt>
"""
import os, sys, json, time, hashlib, re

WL = set(sys.argv[1].split(",")); extra = sorted(set(os.environ) - WL); assert not extra, f"env outside whitelist: {extra}"
TPL, TPL_SHA, AR, ANPZ, OUTC, DIFF = sys.argv[2:8]
POD_ROOT = "/dev/shm/f10_ens_2026-09-23"
PREREG = {"path": "docs/PREREG_f10_seed_ensemble_book_2026-09-23.md", "commit": "45aba1f3f", "sha256": "56acd8320eae43450ba8a6ddfc7a3808bf0f742bcbe76c5d9890be6da6976d92"}
NOW = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 22), b""): h.update(b)
    return h.hexdigest()


def leaves(o, p=""):
    if isinstance(o, dict):
        out = {}
        for k, v in o.items(): out.update(leaves(v, f"{p}.{k}" if p else k))
        return out if o else {p: {}}
    if isinstance(o, list):
        out = {}
        for i, v in enumerate(o): out.update(leaves(v, f"{p}[{i}]"))
        return out if o else {p: []}
    return {p: o}


def diff(a, b):
    la, lb = leaves(a), leaves(b); ks = sorted(set(la) | set(lb))
    return [{"leaf": k, "a": la.get(k, "<absent>"), "b": lb.get(k, "<absent>")} for k in ks if la.get(k, "<absent>") != lb.get(k, "<absent>")]


ALLOWED = [r"^config$", r"^status$", r"^created_utc$", r"^object$", r"^pending(\.|$)", r"^ovn\.role$", r"^f10ens(\.|$)", r"^new_lineage(\.|$)",
           r"^paths\.pod_root$",
           r"^runs\[\d+\]\.(arm|tag|role)$", r"^runs\[\d+\]\.targets\.arm$", r"^runs\[\d+\]\.targets\.sources(\[\d+\]\.(npz|npz_sha256|receipt|receipt_sha256))?$"]

assert sha(TPL) == TPL_SHA, "template config sha"
T = json.load(open(TPL)); R = json.load(open(AR))
assert R["arm"] == "NEW_ENS" and R["roundtrip"]["scaled"]["bitwise_equal"] and R["roundtrip"]["lit"]["bitwise_equal"], "adapter receipt"
assert sha(ANPZ) == R["targets_npz_sha256"], "adapter npz sha vs its receipt"
N = json.loads(json.dumps(T))
N["config"] = "RUN_CONFIG_F10ENS_NEW_ENS_2026-09-23"
N["status"] = ("FROZEN before any number of the F10 seed-ensemble test (prereg 45aba1f3f); arm NEW_ENS; settings byte-identical to "
               "RUN_CONFIG_OVN_NEW_s42_2026-09-23 (162239b6)")
N["created_utc"] = NOW
N["object"] = "F10 seed-ensemble arm NEW_ENS: combo with F10 = equal-weight rank average of seeds 42 and 2027 (ens_build.py), generated by ens_combo.py, through ovn_adapter.py"
N["pending"] = {"(a) targets": "filled: TARGETS_NEW_ENS (adapter round-trip bitwise PASS)", "(b) the other arms": "NEW_s42 / NEW_s2027 = Stage 1's runs (reused, not re-run)"}
N["ovn"]["role"] = "NEW arm NEW_ENS (F10 seed-ensemble test; config derived from OVN NEW_s42)"
N["f10ens"] = {"prereg": PREREG, "derived_from": {"config": os.path.basename(TPL), "sha256": TPL_SHA, "commit": "e6d8f6680"}, "device": "ens_make_config.py",
               "pod_root_reason": "output root only: the template's /dev/shm/ovn_2026-09-23 is Stage 1's directory (read-only for this task)"}
N["paths"]["pod_root"] = POD_ROOT
N["new_lineage"] = {"arm": "NEW_ENS", "adapter_receipt": {"path": AR, "sha256": sha(AR)}, "new_target_receipt": R["adapter"]["new_receipt"], "sources": R["adapter"]["sources"]}
for r in N["runs"]:
    r["arm"] = r["arm"].replace("OVN_NEW_s42", "F10ENS_NEW_ENS"); assert r["arm"] == "F10ENS_NEW_ENS"
    r["tag"] = "F10ENS_NEW_ENS|" + r["tag"].split("|", 1)[1]
    r["role"] = r["role"].replace("NEW arm NEW_s42", "NEW arm NEW_ENS")
    r["targets"]["arm"] = "NEW_ENS"
    r["targets"]["sources"] = [{"npz": ANPZ, "npz_sha256": R["targets_npz_sha256"], "receipt": AR, "receipt_sha256": sha(AR)}]
d = diff(T, N)
bad = [x["leaf"] for x in d if not any(re.search(p, x["leaf"]) for p in ALLOWED)]
assert not bad, f"leaves outside the allowed set (settings would differ): {bad[:10]}"
assert not [k for k, v in leaves(N).items() if v == "PENDING"], "PENDING in config"
assert [r["tag"].split("|", 1)[1] for r in N["runs"]] == [r["tag"].split("|", 1)[1] for r in T["runs"]], "run set / order"
json.dump(N, open(OUTC, "w"), indent=1, ensure_ascii=False)
rc = {"device": "ens_make_config.py", "self_sha256": sha(os.path.abspath(__file__)), "utc": NOW, "prereg": PREREG, "template": {"path": TPL, "sha256": TPL_SHA},
      "config": {"path": OUTC, "sha256": sha(OUTC), "runs": [r["tag"] for r in N["runs"]]}, "allowed_leaves": ALLOWED, "n_differing_leaves": len(d),
      "differing_leaf_names": sorted({re.sub(r"\[\d+\]", "[*]", x["leaf"]) for x in d}), "diff": d,
      "statement": "every differing leaf vs RUN_CONFIG_OVN_NEW_s42_2026-09-23 is a label, the target arm / sources / run naming / lineage, or the output root paths.pod_root; asserted"}
json.dump(rc, open(DIFF, "w"), indent=1, ensure_ascii=False)
print("ENS_MAKE_CONFIG VERDICT=PASS config_sha256", sha(OUTC), "n_differing_leaves", len(d), "diff_receipt_sha256", sha(DIFF), flush=True)
