#!/bin/bash
# R5-02 raw price restore — VERBATIM transcript of the commands run on pod2 on 2026-09-19 (each was issued as `ssh pod2 '<command>'`).
# Devices sit in /workspace/raw_price_fix_2026-09-19/devices/ (byte-identical to this directory; sha256 in
# receipts/SHA256SUMS_pod2_raw_price_fix_2026-09-19.txt). Every device refuses unless the previous step's receipt is PASS.
# Device versions differ between attempts; each receipt records the device self_sha256 that produced it.

# 1. census (rp_census.py 4adfce5a) -> receipts/RP_CENSUS.json PASS
cd /workspace/raw_price_fix_2026-09-19/devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B rp_census.py PATH,HOME,LC_CTYPE 2>&1 | tee ../receipts/rp_census.log | tail -30

# 2. official archives (rp_fetch.py e6ef1b81; ~17 min, one request at a time) -> receipts/RP_FETCH.json PASS, rc=0 at the end of rp_fetch.log
cd /workspace/raw_price_fix_2026-09-19/devices && (setsid nohup env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B rp_fetch.py PATH,HOME,LC_CTYPE > ../receipts/rp_fetch.log 2>&1; echo "rc=$?" >> ../receipts/rp_fetch.log) </dev/null >/dev/null 2>&1 &

# 3a. restore attempt 1 (rp_restore.py 4f8fb5c1) -> RED on the a2 gate definition (kept as RP_RESTORE.attempt1_RED.json)
cd /workspace/raw_price_fix_2026-09-19/devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B rp_restore.py PATH,HOME,LC_CTYPE 2>&1 | tee ../receipts/rp_restore.log | grep -v "cell .* / " | tail -40; echo "rc=${PIPESTATUS[0]}" | tee -a ../receipts/rp_restore.log
# 3b. restore attempt 2 (rp_restore.py da981b33): PASS but its a4 check measured 0 cells (vacuous; kept as RP_RESTORE.attempt2_vacuous_a4.json)
cd /workspace/raw_price_fix_2026-09-19 && cp receipts/RP_RESTORE.json receipts/RP_RESTORE.attempt1_RED.json && cp receipts/rp_restore.log receipts/rp_restore.attempt1_RED.log && mv r_prices_raw_patch.npz work/r_prices_raw_patch.attempt1_RED.npz && cd devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B rp_restore.py PATH,HOME,LC_CTYPE 2>&1 | tee ../receipts/rp_restore.log | grep -v "cell .* / " | tail -22; echo "rc=${PIPESTATUS[0]}" | tee -a ../receipts/rp_restore.log
# 3c. restore attempt 3 (rp_restore.py 1113767b): PASS; a4 measured the 5 y4-NaN cells, but one EXACT cell (MMTUSDT 2025-11-04 12Z, listing bar)
#     was in neither a3 nor a4, and check (d) skipped cells without all 49 closes (kept as RP_RESTORE.attempt3_open_population.json; patch cbf9bbda)
cd /workspace/raw_price_fix_2026-09-19 && cp receipts/RP_RESTORE.json receipts/RP_RESTORE.attempt2_vacuous_a4.json && cp receipts/rp_restore.log receipts/rp_restore.attempt2_vacuous_a4.log && mv r_prices_raw_patch.npz work/r_prices_raw_patch.attempt2_vacuous_a4.npz && cd devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B rp_restore.py PATH,HOME,LC_CTYPE 2>&1 | tee ../receipts/rp_restore.log | grep -v "cell .* / " | grep "a4\|VERDICT\|FAIL"; echo "rc=${PIPESTATUS[0]}" | tee -a ../receipts/rp_restore.log

# 3d. restore attempt 4: RED on a guessed measurement floor (n > 10000; the true population is 4,088) (kept as RP_RESTORE.attempt4_RED_guessed_floor.json)
cd /workspace/raw_price_fix_2026-09-19 && cp receipts/RP_RESTORE.json receipts/RP_RESTORE.attempt3_open_population.json && cp receipts/rp_restore.log receipts/rp_restore.attempt3_open_population.log && mv r_prices_raw_patch.npz work/r_prices_raw_patch.attempt3_open_population.npz && cd devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B rp_restore.py PATH,HOME,LC_CTYPE 2>&1 | tee ../receipts/rp_restore.log | grep -v "cell .* / " | grep "CHECK a\|CHECK d\|VERDICT\|FAIL"; echo "rc=${PIPESTATUS[0]}" | tee -a ../receipts/rp_restore.log
# 3e. restore FINAL (rp_restore.py fdbbd766) -> receipts/RP_RESTORE.json PASS, r_prices_raw_patch.npz 984c2892...
cd /workspace/raw_price_fix_2026-09-19 && cp receipts/RP_RESTORE.json receipts/RP_RESTORE.attempt4_RED_guessed_floor.json && cp receipts/rp_restore.log receipts/rp_restore.attempt4_RED_guessed_floor.log && mv r_prices_raw_patch.npz work/r_prices_raw_patch.attempt4_RED_guessed_floor.npz && cd devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B rp_restore.py PATH,HOME,LC_CTYPE 2>&1 | tee ../receipts/rp_restore.log | grep -v "cell .* / " | grep "CHECK a4\|CHECK d\|VERDICT\|FAIL"; echo "rc=${PIPESTATUS[0]}" | tee -a ../receipts/rp_restore.log

# 4a. corrected price chain attempt 1 (r_prices_raw.py 35b2075d): PASS; diff summary labelled only bound-bar cells as T2 (kept as *.attempt1_T2label_bound_cells_only.*)
cd /workspace/raw_price_fix_2026-09-19/devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B r_prices_raw.py PATH,HOME,LC_CTYPE exact 2>&1 | tee ../receipts/r_prices_raw.log | grep -v "block" | tail -30; echo "rc=${PIPESTATUS[0]}" | tee -a ../receipts/r_prices_raw.log
# 4b. attempt 2 (r_prices_raw.py 07a3deaf) on patch cbf9bbda: PASS; price_logtable_raw.npy bitwise identical to attempt 1 (cmp)
cd /workspace/raw_price_fix_2026-09-19 && cp receipts/R_PRICES_RAW.json receipts/R_PRICES_RAW.attempt1_T2label_bound_cells_only.json && cp receipts/r_prices_raw.log receipts/r_prices_raw.attempt1_T2label_bound_cells_only.log && cp work/price_logtable_raw.npy work/price_logtable_raw.attempt1.npy && cd devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B r_prices_raw.py PATH,HOME,LC_CTYPE exact 2>&1 | tee ../receipts/r_prices_raw.log | grep -v "block" | tail -6; echo "rc=${PIPESTATUS[0]}" | tee -a ../receipts/r_prices_raw.log; cmp ../work/price_logtable_raw.npy ../work/price_logtable_raw.attempt1.npy && echo LOGTABLE_BITWISE_IDENTICAL_TO_ATTEMPT1 && rm ../work/price_logtable_raw.attempt1.npy

# 4c. FINAL (r_prices_raw.py 07a3deaf) on the final patch 984c2892 -> receipts/R_PRICES_RAW.json PASS; logtable bitwise identical to 4b (cmp); fixture refreshed
cd /workspace/raw_price_fix_2026-09-19 && cp receipts/R_PRICES_RAW.json receipts/R_PRICES_RAW.attempt2_superseded_patch_cbf9bbda.json && cp receipts/r_prices_raw.log receipts/r_prices_raw.attempt2_superseded_patch_cbf9bbda.log && cp work/price_logtable_raw.npy work/price_logtable_raw.prev.npy && cd devices && env -i PATH=/usr/bin:/bin HOME=/root nice -n 10 /workspace/venv/bin/python -B r_prices_raw.py PATH,HOME,LC_CTYPE exact 2>&1 | tee ../receipts/r_prices_raw.log | grep -v "block" | tail -7; echo "rc=${PIPESTATUS[0]}" | tee -a ../receipts/r_prices_raw.log; cmp ../work/price_logtable_raw.npy ../work/price_logtable_raw.prev.npy && echo LOGTABLE_BITWISE_IDENTICAL_TO_PREVIOUS && rm ../work/price_logtable_raw.prev.npy; cp ../work/fixture_real_cells.json ../tests/fixture_real_cells.json

# 5. regression test, pod interpreter (Mac: python3 tests/test_rp_counterexamples.py > receipts/test_rp_counterexamples.log)
cd /workspace/raw_price_fix_2026-09-19 && env -i PATH=/usr/bin:/bin HOME=/root /workspace/venv/bin/python -B tests/test_rp_counterexamples.py > receipts/test_rp_counterexamples_pod2.log 2>&1; echo "rc=$? python=$(/workspace/venv/bin/python -c "import sys,numpy;print(sys.version.split()[0],numpy.__version__)")" >> receipts/test_rp_counterexamples_pod2.log
