#!/usr/bin/env python3
"""fresh_tables.py — render the RESULT document's tables straight from the receipts, so no number is transcribed by hand.
Reads FRESH_STATS.json / FRESH_REPORT.json / FRESH_EXT.json (+ the R-P test receipt) and writes one markdown file.
Every cell printed here is read from a receipt; nothing is recomputed.
usage: env -i PATH=/usr/bin:/bin HOME=/root python -B fresh_tables.py PATH,HOME,LC_CTYPE <stats.json> <report.json> <ext.json> <rptest.json> <out.md>
"""
import os, sys, json, hashlib

WL = set(sys.argv[1].split(",")); extra = sorted(set(os.environ) - WL); assert not extra, f"env outside whitelist: {extra}"
ST, RP_, EX, TST, OUT = sys.argv[2:7]


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 22), b""): h.update(b)
    return h.hexdigest()


S = json.load(open(ST)); R = json.load(open(RP_)); E = json.load(open(EX)); T = json.load(open(TST))
PAIRS = [("FRESH_s42", "NEWS_s42"), ("FRESH_s2027", "NEWS_s2027")]
SEGS = ["2023H2", "2024", "2025", "2026"]
L = []
w = L.append
w(f"<!-- generated by fresh_tables.py {sha(os.path.abspath(__file__))[:16]} from")
w(f"     {ST} {sha(ST)[:16]} / {RP_} {sha(RP_)[:16]} / {EX} {sha(EX)[:16]} / {TST} {sha(TST)[:16]} -->")
w("")
w("## 判词")
w("")
w(f"**VERDICT = {S['VERDICT']}** — {S['verdict_rule']}")
w("")
w(f"逐种子未过条款: `{json.dumps(S['failing_by_seed'], ensure_ascii=False)}`")
w("")
w("### F1–F5 实测 vs 门")
w("")
w("| 种子 | F1 判据窗日差(bps/日) | F2 四段正号 | F3 判据窗 maxDD | F4 R-P 触线路径 | F5 三成本格同号 | 全过 |")
w("|---|---|---|---|---|---|---|")
for f, c in PAIRS:
    v = S["rules"][f]
    f3 = v["F3"]["maxdd_5m_judge_path_mean"]; f4 = v["F4"]["halted_paths"]
    cells = " / ".join(f"{k} {v['F5']['cells'][k]['estimate_bps_per_day']:+.3f}" for k in ("fee_x1.25", "slip_x1.5", "fill_x0.9"))
    w(f"| {f} | {v['F1']['estimate_bps_per_day']:+.4f} ({'PASS' if v['F1']['PASS'] else 'FAIL'}, 门 >0) "
      f"| {v['F2']['segments_positive']}/4 ({'PASS' if v['F2']['PASS'] else 'FAIL'}, 门 ≥3) "
      f"| {f3['FRESH']:.4f} vs {f3['NEWS']:.4f} ({'PASS' if v['F3']['PASS'] else 'FAIL'}, 门 FRESH ≥ NEW_S) "
      f"| {f4['FRESH']} vs {f4['NEWS']} ({'PASS' if v['F4']['PASS'] else 'FAIL'}, 门 ≤) "
      f"| {cells} ({'PASS' if v['F5']['PASS'] else 'FAIL'}) "
      f"| **{'PASS' if v['ALL_PASS'] else 'FAIL'}** |")
w("")
w("### F2 逐段点估计(bps/日,FRESH − NEW_S 同种子)")
w("")
w("| 种子 | " + " | ".join(SEGS) + " | 判据窗合并 |")
w("|---|" + "---|" * (len(SEGS) + 1))
for f, c in PAIRS:
    v = S["rules"][f]; sm = v["F2"]["segment_means"]
    w(f"| {f} | " + " | ".join(f"{sm[s]['mean_bps_per_day']:+.4f} ({sm[s]['n_days']}d)" for s in SEGS) + f" | {v['F1']['estimate_bps_per_day']:+.4f} ({v['F1']['n_days']}d) |")
w("")
w("### 30 日块自举区间(照报,不作门)")
w("")
w("| 种子 | 判据窗 97.5% 双侧(bps/日) | 95%(bps/日) | 5 日块敏感性 95% |")
w("|---|---|---|---|")
for f, c in PAIRS:
    i = S["rules"][f]["intervals_report_only"]
    w(f"| {f} | [{i['boot_30d']['ci97.5_two_sided_bps'][0]:+.3f}, {i['boot_30d']['ci97.5_two_sided_bps'][1]:+.3f}] "
      f"| [{i['boot_30d']['ci95_bps'][0]:+.3f}, {i['boot_30d']['ci95_bps'][1]:+.3f}] "
      f"| [{i['boot_5d']['ci95_bps'][0]:+.3f}, {i['boot_5d']['ci95_bps'][1]:+.3f}] |")
w("")
w("## 必报表(不作门)")
w("")
w("### 两臂逐段水平(路径均值;32 路径)")
w("")
w("| 臂 | 段 | 总收益 | Sharpe | maxDD(5m) | 最差日 | 日止损平仓 | 逐名止损 | 换手/gross |")
w("|---|---|---|---|---|---|---|---|---|")
for arm in ("FRESH_s42", "NEWS_s42", "FRESH_s2027", "NEWS_s2027"):
    for s in SEGS + ["judge"]:
        t = S["tables"][arm]["base"][s]["paths"]
        w(f"| {arm} | {s} | {t['total_return']['path_mean']:+.4f} | {t['sharpe']['path_mean']:.3f} | {t['maxdd_5m']['path_mean']:.4f} "
          f"| {t['worst_day']['path_mean']:+.4f} | {t['day_stop_flattens']['path_mean']:.2f} | {t['per_name_stops']['path_mean']:.1f} | {t['turnover_over_gross']['path_mean']:.4f} |")
w("")
w("### King 分数层 IC 按模型年龄(月)")
w("")
w("| 臂 | 测到锚 | 未测(原因) | 平均 IC | 年龄区间(月) | OLS 斜率(IC/月) | 30 日块 95% 区间 |")
w("|---|---|---|---|---|---|---|")
for arm in ("FRESH", "NEWS"):
    k = R["king_ic_by_model_age"][arm]; sl = k["slope"]
    ci = sl.get("ci95"); ci = f"[{ci[0]:+.5f}, {ci[1]:+.5f}]" if isinstance(ci, list) else str(ci)
    w(f"| King {arm} | {k['n_measured']} | {json.dumps(k['not_measured'], ensure_ascii=False)} | {k['mean_ic_all_measured']:+.5f} "
      f"| {k['age_months']['min']:.2f}–{k['age_months']['max']:.2f} | {sl.get('slope_ic_per_month', 'UNMEASURABLE'):+.5f} | {ci} |" if isinstance(sl.get("slope_ic_per_month"), float) else
      f"| King {arm} | {k['n_measured']} | {json.dumps(k['not_measured'], ensure_ascii=False)} | {k['mean_ic_all_measured']:+.5f} | {k['age_months']['min']:.2f}–{k['age_months']['max']:.2f} | {json.dumps(sl)} | — |")
w("")
w("King 逐年龄桶曲线:")
w("")
w("| 臂 | 年龄桶(月) | 锚数 | 平均 IC |")
w("|---|---|---|---|")
for arm in ("FRESH", "NEWS"):
    for k, v in sorted(R["king_ic_by_model_age"][arm]["curve"].items(), key=lambda x: int(x[0])):
        w(f"| King {arm} | {k} | {v['n_anchors']} | {v['mean_ic']:+.5f} |")
w("")
w("### F10 分数层 IC 按模型年龄(月)")
w("")
w("| 臂 | 测到锚 | 平均 IC | 年龄区间(月) | OLS 斜率(IC/月) | 30 日块 95% 区间 |")
w("|---|---|---|---|---|---|")
for key in sorted(R["f10_ic_by_model_age"]):
    k = R["f10_ic_by_model_age"][key]
    if "UNMEASURABLE" in k: w(f"| F10 {key} | — | — | — | {k['UNMEASURABLE']} | — |"); continue
    sl = k["slope"]; ci = sl.get("ci95"); ci = f"[{ci[0]:+.5f}, {ci[1]:+.5f}]" if isinstance(ci, list) else str(ci)
    sv = sl.get("slope_ic_per_month")
    w(f"| F10 {key} | {k['n_measured']} | {k['mean_ic_all_measured']:+.5f} | {k['age_months']['min']:.2f}–{k['age_months']['max']:.2f} | "
      + (f"{sv:+.5f}" if isinstance(sv, float) else json.dumps(sl)) + f" | {ci} |")
w("")
w("### 目标与 NEW_S 的差(§4 交付线)")
w("")
w("| 种子 | 锚数 | 有差异的锚 | 占比 | 发布决定不同的锚 | 平均 L1 | L1 p50 / p90 / max | NEW_S 平均 gross | L1/gross |")
w("|---|---|---|---|---|---|---|---|---|")
for seed in ("42", "2027"):
    d = R["target_difference_vs_news"][f"s{seed}"]; q = d["l1_over_all_anchors"]
    w(f"| s{seed} | {d['n_anchors']} | {d['anchors_with_any_difference']} | {d['share_anchors_different']:.4f} | {d['kind_decision_differs']} "
      f"| {q['mean']:.5f} | {q['p50']:.5f} / {q['p90']:.5f} / {q['max']:.5f} | {d['mean_gross']['NEWS']:.4f} | {d['l1_relative_to_mean_gross']:.4f} |")
w("")
w("### 过链换手(目标层 L1,逐年)")
w("")
w("| 种子 | 年 | 锚数 | FRESH | NEW_S | 比值 |")
w("|---|---|---|---|---|---|")
for seed in ("42", "2027"):
    for y, v in sorted(R["chain_turnover"][f"s{seed}"]["by_year"].items()):
        w(f"| s{seed} | {y} | {v['anchors']} | {v['FRESH_mean_L1_turnover']:.5f} | {v['NEWS_mean_L1_turnover']:.5f} | " + (f"{v['ratio']:.4f} |" if v["ratio"] is not None else "— |"))
w("")
w("### 席位份额逐年均值")
w("")
w("| 臂 | 年 | ready 锚 | king | rev24 | fund |")
w("|---|---|---|---|---|---|")
for arm in ("FRESH", "NEWS"):
    for y, v in sorted(R["seat_shares"][arm]["by_year"].items()):
        if "note" in v: w(f"| {arm} | {y} | 0 | — | — | — |"); continue
        w(f"| {arm} | {y} | {v['ready_anchors']} | {v['king']:.4f} | {v['rev24']:.4f} | {v['fund']:.4f} |")
w("")
w("### F10 准入窗口与丢弃比例(逐臂合计,逐折见收据)")
w("")
w("| 臂 | 折数 | 考虑窗口 | 录取窗口 | 丢弃 | 丢弃比例 |")
w("|---|---|---|---|---|---|")
for key in sorted(R["f10_admission"]):
    t = R["f10_admission"][key]["totals"]
    w(f"| {key} | {R['f10_admission'][key]['n_folds']} | {t['considered_windows']} | {t['accepted_windows']} | {t['rejected_windows']} | {t['rejected_windows']/t['considered_windows']:.4f} |")
w("")
w("### 延伸段 2026-08-31T04Z → 2026-09-18T20Z(只描述)")
w("")
w("| 臂 | 总收益 | Sharpe | maxDD | 最差日 | 换手/gross | vs NEW_S 同种子(bps/日) |")
w("|---|---|---|---|---|---|---|")
for arm in ("FRESH_s42", "NEWS_s42", "FRESH_s2027", "NEWS_s2027"):
    a = E["arms"][arm]
    d = a.get("dbar_vs_NEWS_same_seed_bps_per_day_point")
    w(f"| {arm} | {a['total_return']['path_mean']:+.4f} | {a['sharpe']['path_mean']:.3f} | {a['maxdd_5m']['path_mean']:.4f} "
      f"| {a['worst_day']['path_mean']:+.4f} | {a['turnover_over_gross']['path_mean']:.4f} | " + (f"{d:+.4f} |" if d is not None else "— |"))
w("")
w("## 装置与前置门")
w("")
w(f"- 前置门 P0_same_engine: **{'PASS' if S['preconditions']['P0_same_engine']['PASS'] else 'FAIL'}** "
  f"(两臂全部 20 个格的 device_sha256 / calibration_sha256 / price_pin 一致;每臂 config_sha256 == 其自身配置文件 sha)")
w(f"- 前置门 P1_common_axis: {S['preconditions']['P1_common_axis']['first']} → {S['preconditions']['P1_common_axis']['last']},{S['preconditions']['P1_common_axis']['n']} 锚")
w(f"- R-P 选运行红/绿测试: **{T['VERDICT']}**,基线先绿,{sum(v['refused'] for v in T['mutations'].values())}/{len(T['mutations'])} 个变异按具名理由拒绝")
w(f"- fresh_stats.py self_sha256 `{S['self_sha256']}`;收据 `{ST}` sha256 `{sha(ST)}`")
w(f"- fresh_report.py self_sha256 `{R['self_sha256']}`;fresh_ext.py self_sha256 `{E['self_sha256']}`")
w("")
w("> " + S["interval_statement_verbatim"])
open(OUT, "w").write("\n".join(L) + "\n")
print("FRESH_TABLES written", OUT, sha(OUT), flush=True)
