"""fresh_mech_table.py — DESCRIBE ONLY, no gate, no attribution. Renders the per-segment, per-arm table of the engine's own
path metrics that lead asked for: hold_anchors / turnover_over_gross / fee / funding_paid / price / g / day_stop_flattens /
per_name_stops / halt_anchors. Every number is read out of FRESH_STATS.json's path tables; nothing is recomputed.

It ALSO prints, for every column, whether the FRESH − NEW_S sign is the SAME on both seeds. That check exists because a
description written from one seed can be false as a general statement: the two seeds are two draws of the same comparison,
and a column whose sign flips between them cannot be described as "what co-occurs with FRESH" without naming the flip.
No causal language is produced anywhere in this device's output, by construction: it emits numbers and sign agreement only.

usage: env -i PATH=/usr/bin:/bin HOME=/root python -B fresh_mech_table.py PATH,HOME,LC_CTYPE <FRESH_STATS.json> <out.json> <out.md>
"""
import os, sys, json, hashlib
WL = set(sys.argv[1].split(",")); extra = sorted(set(os.environ) - WL); assert not extra, f"env outside whitelist: {extra}"
STATS, OUT, OUTMD = sys.argv[2:5]
SEGS = ("2023H2", "2024", "2025", "2026", "judge")
COLS = ("hold_anchors", "turnover_over_gross", "fee", "funding_paid", "price", "g", "day_stop_flattens", "per_name_stops", "halt_anchors")
FMT = {"hold_anchors": "{:.1f}", "turnover_over_gross": "{:.4f}", "fee": "{:+.4f}", "funding_paid": "{:+.4f}", "price": "{:+.4f}",
       "g": "{:+.4f}", "day_stop_flattens": "{:.2f}", "per_name_stops": "{:.1f}", "halt_anchors": "{:.1f}"}
SEEDS = ("s42", "s2027")


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 22), b""): h.update(b)
    return h.hexdigest()


def main():
    R = json.load(open(STATS)); T = R["tables"]
    val = lambda arm, seg, c: T[arm]["base"][seg]["paths"][c]["path_mean"]
    rec = {"device": "fresh_mech_table.py", "self_sha256": sha(os.path.abspath(__file__)),
           "status": "DESCRIBE ONLY — no gate, no attribution, no causal claim",
           "reads": {"stats": {"path": STATS, "sha256": sha(STATS)}}, "columns": list(COLS), "table": {}, "seed_sign_agreement": {}}
    for seg in SEGS:
        rec["table"][seg] = {}
        for s in SEEDS:
            for side in ("FRESH", "NEWS"):
                arm = f"{side}_{s}"
                rec["table"][seg][arm] = {c: val(arm, seg, c) for c in COLS}
    # sign agreement of (FRESH − NEW_S) across the two seeds, per segment per column
    for seg in SEGS:
        rec["seed_sign_agreement"][seg] = {}
        for c in COLS:
            d = {s: val(f"FRESH_{s}", seg, c) - val(f"NEWS_{s}", seg, c) for s in SEEDS}
            sg = {s: (0 if d[s] == 0 else (1 if d[s] > 0 else -1)) for s in SEEDS}
            rec["seed_sign_agreement"][seg][c] = {"delta": d, "sign": sg, "AGREE": bool(sg["s42"] == sg["s2027"])}
    flips = [(seg, c) for seg in SEGS for c in COLS if not rec["seed_sign_agreement"][seg][c]["AGREE"]]
    rec["columns_whose_sign_flips_between_seeds"] = [{"segment": seg, "column": c,
                                                      "s42": rec["seed_sign_agreement"][seg][c]["delta"]["s42"],
                                                      "s2027": rec["seed_sign_agreement"][seg][c]["delta"]["s2027"]} for seg, c in flips]
    json.dump(rec, open(OUT + ".tmp", "w"), indent=1, default=float); os.replace(OUT + ".tmp", OUT)

    L = [f"<!-- generated by fresh_mech_table.py {rec['self_sha256'][:16]} from {os.path.basename(STATS)} {sha(STATS)[:16]}; "
         f"DESCRIBE ONLY, no gate, no attribution -->\n"]
    L.append("| 段 | 臂 | hold 锚 | 换手/gross | fee | funding_paid | price | g | 日止损平仓 | 逐名止损 | halt 锚 |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for seg in SEGS:
        for s in SEEDS:
            for side in ("FRESH", "NEWS"):
                arm = f"{side}_{s}"; r = rec["table"][seg][arm]
                L.append(f"| {seg} | {arm} | " + " | ".join(FMT[c].format(r[c]) for c in COLS) + " |")
    L.append("\n**两种子符号是否一致(FRESH − NEW_S)** —— 只有两个种子同号的列,才能当作「与 FRESH 同时出现」的描述来写;"
             "符号在两种子之间翻转的列,必须连翻转一起写出来。\n")
    L.append("| 段 | 列 | s42 的差 | s2027 的差 | 同号? |")
    L.append("|---|---|---|---|---|")
    for seg in SEGS:
        for c in COLS:
            a = rec["seed_sign_agreement"][seg][c]
            L.append(f"| {seg} | {c} | {a['delta']['s42']:+.4f} | {a['delta']['s2027']:+.4f} | {'是' if a['AGREE'] else '**否**'} |")
    open(OUTMD + ".tmp", "w").write("\n".join(L) + "\n"); os.replace(OUTMD + ".tmp", OUTMD)
    print(f"FRESH_MECH_TABLE written {OUT} {sha(OUT)} n_sign_flips={len(flips)} "
          f"hold_anchors_flips={[f['segment'] for f in rec['columns_whose_sign_flips_between_seeds'] if f['column'] == 'hold_anchors']} "
          f"hold_judge_s42={val('FRESH_s42','judge','hold_anchors'):.1f}vs{val('NEWS_s42','judge','hold_anchors'):.1f} "
          f"hold_judge_s2027={val('FRESH_s2027','judge','hold_anchors'):.1f}vs{val('NEWS_s2027','judge','hold_anchors'):.1f}", flush=True)


if __name__ == "__main__":
    main()
