#!/usr/bin/env python3
"""t6_family_tables.py -- render the member / exclusion tables of FAMILY_T6.json as markdown (no statistics)."""
import json, sys, collections, os, hashlib
FJ, OUT = sys.argv[1], sys.argv[2]
F = json.load(open(FJ))
dec = {d["path"]: d for d in F["decisions"]}
L = []
w = L.append
w("## §5 Member tables (generated by `devices/t6_family_tables.py` from `FAMILY_T6.json` sha256 `%s`)\n" % hashlib.sha256(open(FJ, "rb").read()).hexdigest())
w("Columns: id · family flags (1=F1 primary, 2=F2 admission candidates, 3=F3 r8–r21+T2 scope, 4=F4 wide, 5=F5 A0 model inputs) · role · round · canonical record (pod2 path under `/workspace/uplift_2026-09-11/` unless it starts with `R2/` = `/workspace/uplift_r2_2026-09-13/`) · file sha256[:16] · judged rec key · rows (first..last, n) · g_sha256(W_FULL)[:12] · model inputs (king | F10) · citing RESULT · number of bitwise-identical aliases (listed in FAMILY_T6.json).\n")
for seed in ("42", "2027"):
    ms = [m for m in F["members"] if m["seed"] == seed]
    w("\n### Seed %s — %d members (F1 %d · F2 %d · F3 %d · F4 %d · F5 %d)\n" % (seed, len(ms), sum(m["in_F1"] for m in ms), sum(m["in_F2"] for m in ms), sum(m["in_F3"] for m in ms), sum(m["in_F4"] for m in ms), sum(m["in_F5"] for m in ms)))
    w("| id | fam | role | round | canonical record | file sha256 | rec | rows | g_sha | model inputs | cites | aliases |")
    w("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for m in ms:
        fam = "".join(str(i) for i, f in ((1, m["in_F1"]), (2, m["in_F2"]), (3, m["in_F3"]), (4, m["in_F4"]), (5, m["in_F5"])) if f)
        p = m["canonical_path"].replace("/workspace/uplift_2026-09-11/", "").replace("/workspace/uplift_r2_2026-09-13/", "R2/")
        cite = m["cite"].replace("multi_asset/exports/research/uplift_2026-09-11/", "U/").replace("multi_asset/exports/research/uplift_r2_2026-09-13/", "R2/")
        w("| %s | %s | %s | %s | `%s` | `%s` | %s | %s | `%s` | %s | %s | %d |" % (m["member_id"], fam, m["role"], m["canonical_round"], p, m["canonical_file_sha256"][:16], m["rec_key"], m["rows"], m["g_sha256_wfull"][:12], m["model_inputs"].replace("|", " + "), cite, len(m["aliases"])))
w("\n## §6 Every accounting-caliber record file and its decision (counts by round × decision; per-file detail in FAMILY_T6.json `decisions`)\n")
c = collections.Counter()
for d in F["decisions"]:
    tag = d["role"] if d["cls"] == "X" and "EXCL_GRID" not in (d["note"] or "") else (("EXCL_GRID(" + d["role"] + ")") if d["cls"] == "X" else ("INCLUDED_" + d["cls"] + "(" + d["role"] + ")"))
    c[(d["round"], tag)] += 1
w("| round | decision | files |")
w("|---|---|---|")
for (rnd, tag), n in sorted(c.items(), key=lambda kv: (str(kv[0][0]), kv[0][1])):
    w("| %s | %s | %d |" % (rnd, tag, n))
open(OUT, "w").write("\n".join(L) + "\n")
print("SUMMARY t6_family_tables rows=%d out=%s" % (len(L), OUT))
